### PR TITLE
generalized new computed expression

### PR DESCRIPTION
**Pull request by chakravala**
This is a necessary generalization to enable customized `new` expressions for a `@computed` type.
```julia
@macroexpand @computed struct MultiVector{V,𝕂}
    v::Values{1<<mdims(V),𝕂}
end begin
    M = DirectSum.submanifold(V)
    new{M, 𝕂, 1 << mdims(M)}(v)
end
```
@vtjnash Please review and register this update, as I want to use this in [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) in the next release.

### CODE REVIEW

**Comment by vtjnash** [comment]
What is the purpose of this? It seems to expose implementation details, while not exposing anything new:
```julia
julia> @macroexpand @computed struct MultiVector{V,𝕂}
           v::Values{1<<mdims(V),𝕂}
       function MultiVector{V,𝕂}() where {V,𝕂}
           M = DirectSum.submanifold(V)
           new{M, 𝕂}(v)
       end
       end
quote
    struct MultiVector{V, 𝕂, var"##284"}
        #= REPL[3]:2 =#
        v::Values{var"##284", 𝕂}
        #= REPL[3]:3 =#
        function MultiVector{V, 𝕂}() where {V, 𝕂}
            #= REPL[3]:3 =#
            #= REPL[3]:4 =#
            M = DirectSum.submanifold(V)
            #= REPL[3]:5 =#
            new{M, 𝕂, 1 << mdims(V)}(v)
        end
    end
    function ComputedFieldTypes.fulltype(::Base.Type{MultiVector{V, 𝕂}}) where {V, 𝕂}
        return MultiVector{V, 𝕂, 1 << mdims(V)}
    end
end
```

**Comment by chakravala** [comment]
@vtjnash The purpose of it is to customize the `new` expression while retaining the nice simplified syntax of `ComputedFieldTypes`. For my purposes, I found I need to customize the `new` expression method. There are now only two options for me: either to manually create the definitions I wanted without this package, or to add this as an extra parameter to the macro. Having this as a second parameter seems like a nice way to handle it, otherwise I would need to stop using this package.

**Comment by vtjnash** [comment]
I am confused then, since all this seems to do (relative to now) is allow you to compute a different (and therefore probably incorrect) value for the field types. What is the improvement?

**Comment by chakravala** [comment]
@vtjnash, you don't need to accept this pull request if you don't want to, but then I will also stop using your package because I need this modification or I will stop using this package. Whether this is an improvement or not, that is semantics. For me, the only thing that matters is that I am able to specify a custom expression for `newexpr`. Either I will do it manually by creating these definitions without your package, or it can be added as an extra optional custom parameter. At the moment, it looks like I will stop using this package in favor of creating manual definitions instead, unless you are willing to accept this optional parameter.

**Comment by vtjnash** [comment]
I am not opposed, if this is useful, I am just very confused about what it does, and hoping you could show an example of how to use it. Currently it seems to just allow putting incorrectly computed expressions in the computed fields. The package already supports user-defined constructors with user-defined parameter computations for the regularly declared fields, as I show above.

**Comment by chakravala** [comment]
Oh okay, I didn't at first realize that your syntax does support it neatly. Never mind then.

**Pull request closed without merging**
